---
version: 2.1
orbs:
  jq: circleci/jq@2.2.0

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - run: mkdir ./artifacts
      - run:
          name: Create Plugins Zip
          command: zip ./artifacts/stanza-plugins.zip ./plugins/*
      - run:
          name: Create Plugins Tarball
          command: tar -zcvf ./artifacts/stanza-plugins.tar.gz ./plugins/*
      - run:
          name: Write Version File
          command: printf '{"version":"%s"}\n' $CIRCLE_TAG > artifacts/version.json
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GHI_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/

  publish_sources:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - jq/install
      - run:
          name: "Publish sources to the Stanza Source Service"
          command: |
            last_release=$(git describe --abbrev=0 --tags --match 'v*[0-9].*[0-9].*[0-9]' HEAD~1)
            changed_plugins=$(git diff --name-only $last_release ./plugins)
            for i in $changed_plugins ; do 
              if [ ! -f "$i" ] ; then
               