
name: "Test Config"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - name: go test
        run: make test